apps/university/urls.py
from django.conf.urls import url

from . import api, views

urlpatterns = [
    url(r'^$', views.university_overview, name='overview'),
    url(r'^add/$', views.university_add, name='add'),
    url(r'^edit/(?P<id>[0-9]+)$', views.university_edit, name='edit'),
    url(r'^delete/$', api.university_delete, name='delete'),
    ]

students/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    url(r'^university/',
        include('apps.university.urls', namespace='university')),
    url(r'^lector/', include('apps.lector.urls', namespace='lector')),
    url(r'^pupil/', include('apps.pupil.urls', namespace='pupil')),
    url(r'^my_account/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apps.accounts.views.home', name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^resetpassword/passwordsent$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^resetpassword/$', auth_views.password_reset, name="reset_password"),
    url(r'^reset(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done$', auth_views.password_reset_complete, name='password_reset_complete'),
]

apps/university/models.py
from django.db import models


class University(models.Model):
    title = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    city = models.CharField(max_length=60)
    address = models.CharField(max_length=30)
    fax = models.IntegerField(blank=True, null=True)
    phone = models.IntegerField(blank=True, null=True)
    glob_email = models.EmailField(max_length=254)
    num_stud = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "universities"

    def __str__(self):
        return '{} {}'.format(self.title, self.city)


class Contact(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    mobile = models.IntegerField(blank=True, null=True)
    email = models.EmailField(max_length=254)
    remarks = models.CharField(max_length=600, blank=True)
    univer = models.ForeignKey(University, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Subject(models.Model):
    title = models.CharField(max_length=30)
    hours = models.IntegerField(default=30)
    description = models.CharField(max_length=600, blank=True)
    univer = models.ForeignKey(University, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.title)

apps/university/forms.py
from django import forms
from django.forms import ModelForm

from .models import Contact, Subject, University


class UniversityForm(ModelForm):
    class Meta:
        model = University
        fields = ['title', 'country', 'city', 'address',
                  'fax', 'phone', 'glob_email', 'num_stud']
        widgets = {'title': forms.TextInput(attrs={'class': 'form-control'}),
                   'country': forms.TextInput(attrs={'class': 'form-control'}),
                   'city': forms.TextInput(attrs={'class': 'form-control'}),
                   'address': forms.TextInput(attrs={'class': 'form-control'}),
                   'fax': forms.NumberInput(attrs={'class': 'form-control'}),
                   'phone': forms.NumberInput(attrs={'class': 'form-control'}),
                   'glob_email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'num_stud': forms.NumberInput(attrs={'class': 'form-control'})
                   }
        labels = {
            'title': ('Title'),
            'country': ('Country'),
            'city': ('City'),
            'address': ('Address'),
            'fax': ('Fax'),
            'phone': ('Phone'),
            'num_stud': ('Total number of students'),
            'glob_email': ('Global email')
            }


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'mobile', 'email', 'remarks']
        widgets = {'first_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'last_name': forms.TextInput(attrs={'class': 'form-control'}),
                   'mobile': forms.NumberInput(attrs={'class': 'form-control'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'remarks': forms.Textarea(attrs={'class': 'form-control'})
                   }
        labels = {
            'first_name': ('First name'),
            'last_name': ('Last name'),
            'mobile': ('Mobile'),
            'email': ('Email'),
            'remarks': ('Remarks')
            }


class SubjectForm(ModelForm):
    class Meta:
        model = Subject
        fields = ['title', 'hours', 'description']
        widgets = {'title': forms.TextInput(attrs={'class': 'form-control'}),
                   'hours': forms.NumberInput(attrs={'class': 'form-control'}),
                   'description': forms.Textarea(attrs={'class': 'form-control'})
                   }
        labels = {
            'title': ('Subject'),
            'hours': ('Hours'),
            'description': ('Description')
            }

apps/university/views.py
from django.core.urlresolvers import reverse
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from apps.utils.views import render_to

from .forms import ContactForm, SubjectForm, UniversityForm
from .models import Contact, Subject, University


@render_to('university-overview.html')
def university_overview(request):
    if 'query_univ' in request.GET:
        universities = University.objects.filter(
            title__contains=request.GET.get('query_univ'))
    else:
        universities = University.objects.all()
    return {'universities': universities}


@render_to('university-add.html')
def university_add(request):
    ContactFormSet = inlineformset_factory(
        University, Contact, extra=1, form=ContactForm)
    SubjectFormSet = inlineformset_factory(
        University, Subject, extra=1, form=SubjectForm)
    if request.method == 'POST':
        university_form = UniversityForm(request.POST)
        contact_formset = ContactFormSet(request.POST)
        subject_formset = SubjectFormSet(request.POST)
        if (university_form.is_valid() and contact_formset.is_valid() and
                subject_formset.is_valid()):
            instance = university_form.save()
            contact_formset.instance = instance
            subject_formset.instance = instance
            contact_formset.save()
            subject_formset.save()
            return HttpResponseRedirect(reverse('university:overview'))
    else:
        contact_formset = ContactFormSet(queryset=Contact.objects.none())
        subject_formset = SubjectFormSet(queryset=Subject.objects.none())
        university_form = UniversityForm()

    return {'university_form': university_form, 'contact_formset': contact_formset,
            'subject_formset': subject_formset}


@render_to('university-edit.html')
def university_edit(request, id):
    university = get_object_or_404(University, pk=id)
    university_form = UniversityForm(instance=university)
    ContactFormSet = inlineformset_factory(
        University, Contact, extra=0, form=ContactForm)
    contact_formset = ContactFormSet(instance=university)
    SubjectFormSet = inlineformset_factory(
        University, Subject, extra=0, form=SubjectForm)
    subject_formset = SubjectFormSet(instance=university)

    if request.method == 'POST':
        university_form = UniversityForm(request.POST, instance=university)
        university = university_form.save(commit=False)
        contact_formset = ContactFormSet(request.POST, instance=university)
        subject_formset = SubjectFormSet(request.POST, instance=university)
        if (university_form.is_valid() and contact_formset.is_valid() and
                subject_formset.is_valid()):
            university_form.save()
            contact_formset.save()
            subject_formset.save()
            return HttpResponseRedirect(reverse('university:overview'))

    return {'university_form': university_form, 'contact_formset': contact_formset,
            'subject_formset': subject_formset}


def university_delete(request, id):
    instance = get_object_or_404(University, pk=id)
    Contact.objects.filter(unversity=instance).delete()
    University.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('university:overview'))


def contact_delete(request, id):
    Contact.objects.get(pk=id).delete()
    return HttpResponseRedirect(reverse('university:overview'))

templates/university/university-add.html
{% extends "base.html" %}
{% block title %}<h1><a href="{% url 'university:overview' %}">Universities</a></h1>{% endblock %}
{% block content %}

<div id="empty_form_contact" style="display:none">
  <div class="panel panel-info contact">
    <div class="panel-heading">
      <h2 class="col-md-10">Contact person</h2>
    </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
           <div class="col-md-3 form-group">
             {{ contact_formset.empty_form.first_name.label_tag }}
             {{ contact_formset.empty_form.first_name.errors }}
             {{ contact_formset.empty_form.first_name }}

             {{ contact_formset.empty_form.last_name.label_tag }}
             {{ contact_formset.empty_form.last_name.errors }}
             {{ contact_formset.empty_form.last_name }}

             {{ contact_formset.empty_form.mobile.label_tag }}
             {{ contact_formset.empty_form.mobile.errors }}
             {{ contact_formset.empty_form.mobile }}

             {{ contact_formset.empty_form.email.label_tag }}
             {{ contact_formset.empty_form.email.errors }}
             {{ contact_formset.empty_form.email }}
           </div>
           <div class="col-md-6 form-group">
             {{ contact_formset.empty_form.remarks.label_tag }}
             {{ contact_formset.empty_form.remarks.errors }}
             {{ contact_formset.empty_form.remarks }}
           </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="empty_form_subject" style="display:none">
    <div class="panel panel-info subject">
      <div class="panel-heading">
        <h2 class="col-md-10">Subject</h2>
      </div>
        <div class="panel-body no-padding-bottom">
          <div class="tab-content">
            <div class="row">
             <div class="col-md-3 form-group">
               {{ subject_formset.empty_form.title.label_tag }}
               {{ subject_formset.empty_form.title.errors }}
               {{ subject_formset.empty_form.title }}

               {{ subject_formset.empty_form.university.label_tag }}
               {{ subject_formset.empty_form.university.errors }}
               {{ subject_formset.empty_form.university }}

               {{ subject_formset.empty_form.hours.label_tag }}
               {{ subject_formset.empty_form.hours.errors }}
               {{ subject_formset.empty_form.hours }}

            </div>
             <div class="col-md-6 form-group">
               {{ subject_formset.empty_form.description.label_tag }}
               {{ subject_formset.empty_form.description.errors }}
               {{ subject_formset.empty_form.description }}
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  <form action='' id="add_univer" method='POST'>
    {% csrf_token %}
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="col-md-10">University Info</h2>
      </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
            <div class="col-md-3 form-group">
              {{ university_form.title.label_tag }}
              {{ university_form.title.errors }}
              {{ university_form.title }}

              {{ university_form.num_stud.label_tag }}
              {{ university_form.num_stud.errors }}
              {{ university_form.num_stud }}
            </div>
            <div class="col-md-3 form-group">

              {{ university_form.country.label_tag }}
              {{ university_form.country.errors }}
              {{ university_form.country }}

              {{ university_form.city.label_tag }}
              {{ university_form.city.errors }}
              {{ university_form.city }}

              {{ university_form.address.label_tag }}
              {{ university_form.address.errors }}
              {{ university_form.address }}
            </div>
            <div class="col-md-3 form-group">

              {{ university_form.phone.label_tag }}
              {{ university_form.phone.errors }}
              {{ university_form.phone }}

              {{ university_form.fax.label_tag }}
              {{ university_form.fax.errors }}
              {{ university_form.fax }}

              {{ university_form.glob_email.label_tag }}
              {{ university_form.glob_email.errors }}
              {{ university_form.glob_email }}
            </div>
          </div>
        </div>
      </div>
    </div>

    {{ contact_formset.management_form }}

     <div id="contact_form_set">
       {% for contactform in contact_formset %}
         <div class="panel panel-info">
           <div class="panel-heading">
             <h2 class="col-md-10">Contact person</h2>
           </div>
           <div class="panel-body no-padding-bottom">
             <div class="tab-content">
               <div class="col-md-3 form-group">
                 <div class="row">
                   {{ contactform.first_name.label_tag }}
                   {{ contactform.first_name.errors}}
                   {{ contactform.first_name }}
                 </div>
                 <div class="row">
                   {{ contactform.last_name.label_tag }}
                   {{ contactform.last_name.errors }}
                   {{ contactform.last_name }}
                 </div>
                 <div class="row">
                   {{ contactform.mobile.label_tag }}
                   {{ contactform.mobile.errors }}
                   {{ contactform.mobile }}
                 </div>
                 <div class="row">
                   {{ contactform.email.label_tag }}
                   {{ contactform.email.errors }}
                   {{ contactform.email }}
                 </div>
               </div>
               <div class="col-md-6 form-group">
                 {{ contactform.remarks.label_tag }}
                 {{ contactform.remarks.errors}}
                 {{ contactform.remarks }}
               </div>
             </div>
           </div>
         </div>
       {% endfor %}
      </div>
      <div class="col-md form-group">
        <input type="button" class="btn btn-primary" value="+" id="add_contact">
        <input type="button" class="btn btn-danger" value="-" id="delete_contact">
      </div>
      {{ subject_formset.management_form }}

       <div id="subject_form_set">
         {% for subjectform in subject_formset %}
           <div class="panel panel-info">
             <div class="panel-heading">
               <h2 class="col-md-10">Subject</h2>
             </div>
             <div class="panel-body no-padding-bottom">
               <div class="tab-content">
                 <div class="col-md-3 form-group">
                   <div class="row">
                     {{ subjectform.title.label_tag }}
                     {{ subjectform.title.errors}}
                     {{ subjectform.title }}
                   </div>
                   <div class="row">
                     {{ subjectform.hours.label_tag }}
                     {{ subjectform.hours.errors }}
                     {{ subjectform.hours }}
                   </div>
                 </div>
                 <div class="col-md-6 form-group">
                   {{ subjectform.description.label_tag }}
                   {{ subjectform.description.errors}}
                   {{ subjectform.description }}
                 </div>
               </div>
             </div>
           </div>
         {% endfor %}
        </div>
        <div class="col-md form-group">
          <input type="button" class="btn btn-primary" value="+" id="add_subject">
          <input type="button" class="btn btn-danger" value="-" id="delete_subject">
      </form>
          <button type="submit" form="add_univer" value="OK" class="btn btn-success btn-md">Submit</button>
        </div>
{% endblock %}

{% block extra_script %}
  <script>
     $("#add_contact").click(function() {
         var form_idx = $('#id_contact_set-TOTAL_FORMS').val();
         $('#contact_form_set').append($('#empty_form_contact').html().replace(/__prefix__/g, form_idx));
         $('#id_contact_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
     });

     $("#delete_contact").click(function() {
       var form_idx = $('#id_contact_set-TOTAL_FORMS').val();
       if ($('#id_contact_set-TOTAL_FORMS').val() > 1 && $('.panel.panel-info.contact:last').id !== 'empty_form_contact')
       {
           $('.panel.panel-info.contact:last').remove();
           $('#id_contact_set-TOTAL_FORMS').val(parseInt(form_idx) - 1);
       }
     });

     $("#add_subject").click(function() {
         var form_idx = $('#id_subject_set-TOTAL_FORMS').val();
         $('#subject_form_set').append($('#empty_form_subject').html().replace(/__prefix__/g, form_idx));
         $('#id_subject_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
     });

     $("#delete_subject").click(function() {

       var form_idx = $('#id_subject_set-TOTAL_FORMS').val();
       if ($('#id_subject_set-TOTAL_FORMS').val() > 1 && $('.panel.panel-info.subject:last').id !== 'empty_form_subject')
       {
           $('.panel.panel-info.subject:last').remove();
           $('#id_subject_set-TOTAL_FORMS').val(parseInt(form_idx) - 1);
       }
     });
  </script>
{% endblock extra_script %}

templates/university/university-overview.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}<h1>Universities overview</h1>{% endblock %}

{% block content %}

<div class="panel panel-info">
  <div class="panel-heading">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        <i class="fa fa-search save_panel"></i>
      </button>
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="exampleModalLabel">Find by title</h4>
            </div>
            <form action='' method='GET'>
              <div class="modal-body">
                  <div class="form-group">
                    <label for="recipient-name" class="control-label">Your word:</label>
                    <input type="text" class="form-control" id="search-title" name='query_univ'>
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Find</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'university:add' %}">
      <button class="btn btn-success">
          <i class="fa fa-plus-square" aria-hidden="true"></i>
      </button>
      </a>
    </div>

  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      {% if not universities %}
        <p>{% trans "Please add some universities" %}</p>
      {% else %}
        <table class="table table-bordered table-striped table-condensed">
          <thead>
            <tr>
              <th>{% trans 'Title' %}</th>
              <th>{% trans 'City' %}</th>
              <th>{% trans 'Country' %}</th>
              <th>{% trans 'Address' %}</th>
              <th>{% trans 'Fax' %}</th>
              <th>{% trans 'Phone' %}</th>
              <th>{% trans 'Email' %}</th>
              <th>{% trans 'Total number of students' %}</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for university in universities %}

                <tr id = '{{ university.id }}'>
                  <td>{{ university.title }}</td>
                  <td>{{ university.city }}</td>
                  <td>{{ university.country }}</td>
                  <td>{{ university.address }} </td>
                  <td>{{ university.fax }}</td>
                  <td>{{ university.phone }}</td>
                  <td>{{ university.glob_email }}</td>
                  <td>{{ university.num_stud }}</td>
                  <td>
                      <a href="{% url 'university:edit' university.id %}">
                          <button class="btn btn-primary">
                              <i class="fa fa-pencil-square"></i>
                          </button>
                      </a>
                      <button data="{{ university.id }}" class="btn btn-danger remove-iniv" id=delete>
                              <i class="fa fa-trash-o"></i>
                      </button>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

{% block extra_script %}
<script>

$('.remove-iniv').click(function(){
   univ_id = $(this).attr('data');
   //var id = {{ university.id }};
   $.ajax({type: "POST",
          url: "{% url 'university:delete' %}",
          data: {university_id: univ_id },
          success: function(){
            $('#'+univ_id).remove();

      }});
});
</script>
{% endblock extra_script %}