apps/lector/urls.py
from django.conf.urls import url

from . import api, views

urlpatterns = [
    url(r'^$', views.lector_overview, name='overview'),
    url(r'^add/$', views.lector_add, name='add'),
    url(r'^add_subject/$', api.add_subject, name='add_subject'),
    url(r'^edit/(?P<id>[0-9]+)$', views.lector_edit, name='edit'),
    url(r'^delete/$', api.lector_delete, name='delete'),
    url(r'^calendar/$', views.calendar, name='calendar'),
    url(r'^get_events$', views.get_events, name='get_events'),
    url(r'^set_events$', views.set_events, name='set_events'),
    url(r'^resize_events$', views.resize_events, name='resize_events'),
    url(r'^edit_events$', views.edit_events, name='edit_events'),
]

students/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    url(r'^university/',
        include('apps.university.urls', namespace='university')),
    url(r'^lector/', include('apps.lector.urls', namespace='lector')),
    url(r'^pupil/', include('apps.pupil.urls', namespace='pupil')),
    url(r'^my_account/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apps.accounts.views.home', name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^resetpassword/passwordsent$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^resetpassword/$', auth_views.password_reset, name="reset_password"),
    url(r'^reset(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done$', auth_views.password_reset_complete, name='password_reset_complete'),
]

apps/lector/models.py
from django.db import models


class Lector(models.Model):
    subject = models.ManyToManyField('university.Subject')

    def __str__(self):
        return '{}'.format(self.id)


class Event(models.Model):
    title = models.TextField(blank=True)
    start = models.DateTimeField(blank=True, null=True)
    end = models.DateTimeField(blank=True, null=True)
    allDay = models.BooleanField(default=False)
    lector = models.ForeignKey(Lector, null=True)
    is_cancelled = models.BooleanField(default=False)

    def __str__(self):
        return '{}'.format(self.title)

apps/lector/forms.py
from django import forms
from django.forms import ModelForm

from .models import Lector


class LectorForm(ModelForm):
    class Meta:
        model = Lector
        fields = ['subject']
        widgets = {'subject': forms.CheckboxSelectMultiple()}

apps/lector/views.py
import json
from datetime import datetime, timedelta

import timestring
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt

from apps.accounts.forms import AccountForm
from apps.accounts.models import Account
from apps.utils.views import render_json, render_to

from .forms import LectorForm
from .models import Event


@render_to('lector-overview.html')
def lector_overview(request):
    all_lector = Account.objects.all().filter(lector__isnull=False)
    if 'query_lector' in request.GET:
        lectors = all_lector.objects.filter(
            first_name__contains=request.GET.get('query_lector'))
    else:
        lectors = all_lector
    return {'lectors': lectors}


@render_to('lector-add.html')
def lector_add(request):
    if request.method == 'POST':
        account_form = AccountForm(request.POST)
        lector_form = LectorForm(request.POST)
        if lector_form.is_valid() and account_form.is_valid():
            account = account_form.save()
            lector = lector_form.save(commit=False)
            account.lector = lector
            account.save()

            return HttpResponseRedirect(reverse('lector:overview'))
    else:
        lector_form = LectorForm()
        account_form = AccountForm()

    return {'lector_form': lector_form, 'account_form': account_form}


@render_to('lector-edit.html')
def lector_edit(request, id):
    lector = get_object_or_404(Account, pk=id)
    lector_form = AccountForm(instance=lector)

    if request.method == 'POST':
        lector_form = AccountForm(request.POST, instance=lector)
        lector = lector_form.save(commit=False)
        if lector_form.is_valid():
            lector_form.save()
            return HttpResponseRedirect(reverse('lector:overview'))

    return {'lector_form': lector_form}


@csrf_exempt
def get_events(request):
    events = Event.objects.all()
    event_list = []
    for event in events:
        event_start = event.start.astimezone(timezone.get_default_timezone())
        event_end = event.end.astimezone(timezone.get_default_timezone())
        if event_start.hour == 0 and event_start.minute == 0:
            allDay = True
        else:
            allDay = False
        if not event.is_cancelled:
            event_list.append({
                'id': event.id,
                'start': event_start.strftime('%Y-%m-%d %H:%M:%S'),
                'end': event_end.strftime('%Y-%m-%d %H:%M:%S'),
                'title': event.title,
                'allDay': allDay
            })
    if len(event_list) == 0:
        raise Http404
    else:
        return HttpResponse(json.dumps(event_list),
                            content_type='application/json')


@csrf_exempt
@render_json
def set_events(request):
    if request.method == 'POST' and request.is_ajax():
        start = str(timestring.Date(request.POST.get('start')))
        end = str(timestring.Date(request.POST.get('end')))
        event = Event.objects.create(id=request.POST.get('event_id'),
                                     title=request.POST.get('title'),
                                     start=start,
                                     end=end)
        event_data = (event.id, event.title, start, end)
        return {'success': True, 'data': {'event_data': event_data}}
    return {'success': False}


@csrf_exempt
@render_json
def resize_events(request):
    if request.is_ajax() and request.method == 'POST':
        new = datetime.strptime(request.POST.get(
            'end'), "%Y-%m-%d %H:%M:%S") + timedelta(milliseconds=int(request.POST.get('delta')))

        event = Event.objects.filter(id=request.POST.get('event_id'))[0]
        event.end = new
        event.save()
        return {'success': True, 'data': {'event_id': event.id}}
    return {'success': False}


@csrf_exempt
@render_json
def edit_events(request):
    if request.is_ajax() and request.method == 'POST':
        if request.POST.get('status') == 'delete':
            event = Event.objects.filter(id=request.POST.get('event_id'))[0]
            event.delete()
        elif request.POST.get('status') == 'edit':
            event = Event.objects.filter(id=request.POST.get('event_id'))[0]
            event.title = request.POST.get('title')
            event.save()
        return {'success': True, 'data': {'event_id': event.id}}
    return {'success': False}


@render_to('calendar.html')
def calendar(request):
    return {}

templates/lector/calendar.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <link href="{% static 'css/fullcalendar.css' %}" rel="stylesheet">
  <link href="{% static 'cupertino/jquery-ui.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/moment.min.js' %}"></script>
  <script src="{% static 'js/fullcalendar.min.js' %}"></script>
  <script>
  	$(document).ready(function() {
  		$('#calendar').fullCalendar({
        theme: true,
  			header: {
  				left: 'prev,next today',
  				center: 'title',
  				right: 'month,agendaWeek,agendaDay'
  			},
        minTime: "8:00:00",
        maxTime : "24:00:00",
        slotEventOverlap: false,
        defaultView: 'agendaWeek',
  			selectable: true,
  			selectHelper: true,
        columnFormat: {
            week: 'ddd d/M'
        },
        allDaySlot: false,
        firstDay: 1,
        editable: true,
   			eventLimit: true, // allow "more" link when too many events
        eventStartEditable: false,
        events: "{% url 'lector:get_events' %}",
        timezone: "local",
        select: function(start, end, event, jsEvent, view) {
          var title = prompt('Event Title:', event.title, { buttons: { Ok: true, Cancel: false} });
          if (title){
            event.title = title;
          }
          $.ajax({
            url: "{% url 'lector:set_events' %}",
            type: 'POST',
            data: {
              event_id: event.id,
              start: start._d,
              end: end._d,
              title: event.title
            },
            success: function(response){
                    console.log(events);
              $('#calendar').fullCalendar();
            },
            error: function(e){
              alert('Error processing your request: ' + e.responseText);
            }
          });
        },

        eventResize: function(event, delta, revertFunc) {
          $.ajax({
            url: "{% url 'lector:resize_events' %}",
            type: 'POST',
            data: {
              event_id: event.id,
              end: event.end._i,
              delta: delta._milliseconds,
            },
            success: function(response){
              $('#calendar').fullCalendar('updateEvent', event);
            },
            error: function(e){
              alert('Error processing your request: ' + e.responseText);
           }
         });
        },

        eventRender: function (event, element) {
          element.attr('href', 'javascript:void(0);');
          element.click(function() {
            $("#startTime").html(moment(event.start).format('MMM Do h:mm A'));
            $("#endTime").html(moment(event.end).format('MMM Do h:mm A'));
            $("#eventInfo").html(event.description);
            $("#eventLink").attr('href', event.url);
            $("#eventContent").dialog({
              modal: true,
              title: event.title,
              width:350,
              buttons: {
                Edit: function() {
                  var title = $("#edit_title").val();
                  if (title){
                    event.title = title;
                  }
                  $.ajax({
                    url: "{% url 'lector:edit_events' %}",
                    type: 'POST',
                    data: {
                      status: 'edit',
                      event_id: event.id,
                      title: event.title,
                    },
                    success: function(response){
                      $('#calendar').fullCalendar('updateEvent', event);
                    }
                  });
                  $( this ).dialog( "close" );
                },

                Delete: function() {
                  $.ajax({
                    url: "{% url 'lector:edit_events' %}",
                    type: 'POST',
                    data: {
                      status: 'delete',
                      event_id: event.id,
                    },
                    success: function(response){
                      $('#calendar').fullCalendar('removeEvents', event.id);
                    },
                  });
                  $( this ).dialog( "close" );
                },
              }
               
            });
          });
        },


        // eventClick: function(event, jsEvent, view) {
        //   console.log(event);
        //   var title = prompt('Event Rename:', event.title, { buttons: { Ok: true, Cancel: false} });
        //   if (title){
        //     event.title = title;
        //   }
        //   $.ajax({
        //     url: "{% url 'lector:edit_events' %}",
        //     type: 'POST',
        //     data: {
        //       title: event.title,
        //     },
        //     success: function(response){
        //       if(response.status == 'success')
        //       $('#calendar').fullCalendar('updateEvent',event);
        //     },
        //     error: function(e){
        //       alert('Error processing your request: ' + e.responseText);
        //     }
        //   });
        // }

      });
  	});

  </script>

  <style>
    #calendar {
        max-width: 900px;
        margin: 0 auto;
    }
  </style>

  <div id='calendar'></div>

  <div id="eventContent" title="Event Details" style="display:none;">
    Start: <span id="startTime"></span><br>
    End: <span id="endTime"></span><br><br>
    <p id="eventInfo"></p>
    <p><strong><a id="eventLink" href="" target="_blank">Read More</a></strong></p>
    <input type="text" class="form-control" id="edit_title">
  </div>

{% endblock %}

templates/lector/lector-add.html
{% extends "base.html" %}
{% block title %}<h1><a href="{% url 'lector:overview' %}">Lectors overview</a></h1>{% endblock %}
{% load l10n %}
{% block content %}

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <form action='' id="add_lector" method='POST'>
    {% csrf_token %}
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="col-md-10">Add lector info</h2>
      </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
            <div class="col-md-3 form-group">
              {{ account_form.first_name.label_tag }}
              {{ account_form.first_name.errors }}
              {{ account_form.first_name }}

              {{ account_form.last_name.label_tag }}
              {{ account_form.last_name.errors }}
              {{ account_form.last_name }}

              {{ account_form.mobile.label_tag }}
              {{ account_form.mobile.errors }}
              {{ account_form.mobile }}

              {{ account_form.email.label_tag }}
              {{ account_form.email.errors }}
              {{ account_form.email }}
            </div>
            <div class="col-md-3 form-group">
              {{ account_form.remarks.label_tag }}
              {{ account_form.remarks.errors }}
              {{ account_form.remarks }}
            </div>
            <div class="col-md-3 form-group">
              {{ account_form.univer.label_tag }}
              {{ account_form.univer.errors }}
              {{ account_form.univer }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-info" id="subjects_panel" style="display:none">
     <div class="panel-heading">
       <h2 class="col-md-10">Subjects</h2>
       </div>
       <div class="panel-body no-padding-bottom">
         <div class="tab-content" id="subjects">

         </div>
       </div>
     </div>
     <button type="submit" form="add_lector" value="OK" class="btn btn-success btn-md">Save</button>

{% endblock %}

{% block extra_script %}
  <script>
     $('#univer_lector').change(function() {
     $('#subjects').empty();

     $.ajax({
         url: "{% url 'lector:add_subject' %}",
         type: "GET",
         data: { university: $(this).val() },

         success: function(responce) {
           responce.data.subjects.forEach(function(entry) {
             $("#subjects").append("<label><input type='checkbox' name='subject' value="+entry[0]+"> "+entry[1]+"</label><br>");
           });
           $('#subjects_panel').attr("style", "display:block");
         }
     });
   });
  </script>
</form>
{% endblock extra_script %}

templates/lector/lector-edit.html
{% extends "base.html" %}
{% block title %}<h1><a href="{% url 'lector:overview' %}">Lectors</a></h1>{% endblock %}
{% load l10n %}
{% block content %}

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <form action='' id="edit_lector" method='POST'>
    {% csrf_token %}
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="col-md-10">Edit lector info</h2>
      </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
            <div class="col-md-3 form-group">
              {{ lector_form.first_name.label_tag }}
              {{ lector_form.first_name.errors }}
              {{ lector_form.first_name }}

              {{ lector_form.last_name.label_tag }}
              {{ lector_form.last_name.errors }}
              {{ lector_form.last_name }}

              {{ lector_form.mobile.label_tag }}
              {{ lector_form.mobile.errors }}
              {{ lector_form.mobile }}

              {{ lector_form.email.label_tag }}
              {{ lector_form.email.errors }}
              {{ lector_form.email }}
            </div>
            <div class="col-md-3 form-group">
              {{ lector_form.remarks.label_tag }}
              {{ lector_form.remarks.errors }}
              {{ lector_form.remarks }}
            </div>
            <div class="col-md-3 form-group">
              {{ lector_form.univer.label_tag }}
              {{ lector_form.univer.errors }}
              {{ lector_form.univer }}
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="panel panel-info" id="subjects_panel">
     <div class="panel-heading">
       <h2 class="col-md-10">Subjects</h2>
       </div>
       <div class="panel-body no-padding-bottom">
         <div class="tab-content" id="subjects">
           {% for subject in lector_form.subject %}
             {{ subject }}
             <br>
           {% endfor %}
         </div>
       </div>
     </div>
   </form>

    <button type="submit" form="edit_lector" value="OK" class="btn btn-success btn-md">Update</button>

{% endblock %}

{% block extra_script %}
<script>
   $('#univer_lector').change(function() {
   $('#subjects').empty();

   $.ajax({
       url: "{% url 'lector:add_subject' %}",
       type: "GET",
       data: { university: $(this).val() },

       success: function(responce) {
         responce.data.subjects.forEach(function(entry) {
           if (entry[2])
              $("#subjects").append("<label><input type='checkbox' name='subject' value="+entry[0]+" checked> "+entry[1]+"</label><br>");
           else
              $("#subjects").append("<label><input type='checkbox' name='subject' value="+entry[0]+"> "+entry[1]+"</label><br>");
         });
         $('#subjects_panel').attr("style", "display:block");
       }
   });
 });
</script>
{% endblock extra_script %}

templates/lector/lector-overview.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}<h1>Lectors overview</h1>{% endblock %}

{% block content %}

<div class="panel panel-info">
  <div class="panel-heading">
    <form class="form-inline pull-right" role="form">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search..." name='query_lector'>
      </div>
    </form>
    <a href="{% url 'lector:add' %}">
    <button class="btn btn-success">
        <i class="fa fa-plus-square" aria-hidden="true"></i>
    </button>
    </a>
  </div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      {% if not lectors %}
        <p>{% trans "Please add some lectors" %}</p>
      {% else %}
        <table class="table table-bordered table-striped table-condensed">
          <thead>
            <tr>
              <th>{% trans 'First Name' %}</th>
              <th>{% trans 'Last Name' %}</th>
              <th>{% trans 'Mobile' %}</th>
              <th>{% trans 'Email' %}</th>
              <th>{% trans 'Remarks' %}</th>
              <th>{% trans 'University' %}</th>
              <th>{% trans 'Subjects' %}</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for lector in lectors %}

                <tr id = '{{ lector.id }}'>
                  <td>{{ lector.first_name }}</td>
                  <td>{{ lector.last_name }}</td>
                  <td>{{ lector.mobile }} </td>
                  <td>{{ lector.email }}</td>
                  <td>{{ lector.remarks }}</td>
                  <td>{{ lector.univer }}</td>
                  <!-- <td>{% for subject in lector.subject.all %} {{subject}} {% endfor %}</td> -->
                  <td>
                      <a href="{% url 'lector:edit' lector.id %}">
                          <button class="btn btn-primary">
                              <i class="fa fa-pencil-square"></i>
                          </button>
                      </a>
                      <button data="{{ lector.id }}" class="btn btn-danger remove-iniv" id=delete>
                              <i class="fa fa-trash-o"></i>
                          </button>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

{% block extra_script %}
<script>

$('.remove-iniv').click(function(){
   lect_id = $(this).attr('data');
   $.ajax({type: "POST",
          url: "{% url 'lector:delete' %}",
          data: {lector_id: lect_id },
          success: function(){
            $('#'+lect_id).remove();

      }});
});
</script>
{% endblock extra_script %}