apps/pupil/urls.py
from django.conf.urls import url

from . import api, views
from .forms import GroupForm1, GroupForm2, GroupForm3

urlpatterns = [
    url(r'^$', views.pupil_overview, name='overview'),
    url(r'^add/$', views.pupil_add, name='add'),
    url(r'^add_subject/$', api.add_subject, name='add_subject'),
    url(r'^edit/(?P<id>\d+)$', views.pupil_edit, name='edit'),
    url(r'^delete/$', api.pupil_delete, name='delete'),
    url(r'^group/$', views.GroupWizard.as_view([GroupForm1, GroupForm2, GroupForm3]), name='group'),
    url(r'^group/done/$', views.success_group_creation, name='group_success'),
    url(r'^group/overview/$', views.group_overview, name='group_overview'),
    url(r'^group/edit/(?P<id>\d+)$', views.group_edit, name='group_edit'),
    url(r'^group/delete/$', api.group_delete, name='group_delete'),
    ]

students/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    url(r'^university/',
        include('apps.university.urls', namespace='university')),
    url(r'^lector/', include('apps.lector.urls', namespace='lector')),
    url(r'^pupil/', include('apps.pupil.urls', namespace='pupil')),
    url(r'^my_account/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apps.accounts.views.home', name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^resetpassword/passwordsent$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^resetpassword/$', auth_views.password_reset, name="reset_password"),
    url(r'^reset(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done$', auth_views.password_reset_complete, name='password_reset_complete'),
]

templates/group/done.html
{% extends "base.html" %}
{% load l10n %}
{% block content %}
  <h2>Your group is successfully added</h2>
  <a href="{% url 'pupil:group_overview' %}">Groups overview</a>
{% endblock %}

templates/group/group-edit.html
{% extends "base.html" %}
{% block title %}<h1><a href="{% url 'pupil:group_overview' %}">Groups</a></h1>{% endblock %}
{% load l10n %}
{% block content %}

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

  <form action='' id="edit_group" method='POST'>
    {% csrf_token %}
    <div class="panel panel-info">
      <div class="panel-heading">
        <h2 class="col-md-10">Add group info</h2>
      </div>
      <div class="panel-body no-padding-bottom">
        <div class="tab-content">
          <div class="row">
            <div class="col-md-3 form-group">
              {{ group_form.univer.label_tag }}
              {{ group_form.univer.errors }}
              {{ group_form.univer }}

              {{ group_form.curator.label_tag }}
              {{ group_form.curator.errors }}
              {{ group_form.curator }}

              {{ group_form.department.label_tag }}
              {{ group_form.department.errors }}
              {{ group_form.department }}
            </div>
            <div class="col-md-3 form-group">
              {{ group_form.maximum.label_tag }}
              {{ group_form.maximum.errors }}
              {{ group_form.maximum }}

              {{ group_form.minimum.label_tag }}
              {{ group_form.minimum.errors }}
              {{ group_form.minimum }}
            </div>
            <div class="col-md-3 form-group">
              {{ group_form.subject.label_tag }}
              {{ group_form.subject.errors }}
              {{ group_form.subject }}
            </div>
            <div class="col-md-3 form-group">
              {{ group_form.pupils.label_tag }}
              {{ group_form.pupils.errors }}
              {{ group_form.pupils }}
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>

  <button type="submit" form="edit_group" value="OK" class="btn btn-success btn-md">Update</button>

{% endblock %}

templates/group/group-form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}<h1><a href="{% url 'pupil:group_overview' %}">Groups overview</a></h1>{% endblock %}
{% load l10n %}
{% block content %}
  <h2>Group</h2>
  <p> Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
  {% for field in form %}
    {{ field.error }}

  {% endfor %}

  <form action='{% url "pupil:group" %}' method="post">
    {% csrf_token %}
    <table>
    {{ wizard.management_form }}
    {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            {{ form }}
        {% endfor %}
    {% else %}
        {{ wizard.form }}
    {% endif %}
    </table>





    {% if wizard.steps.prev %}
    <ul class="pager">
      <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}"
       class="btn btn-primary btn-sm">To the beginning</button>
       <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.last }}"
        class="btn btn-primary btn-sm">To the end</button>
    </ul>
      <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}"
       class="btn btn-primary btn-sm">Previous</button>
    {% endif %}
      <input type="submit" value="Next" class="btn btn-success btn-sm"/>

  </form>









  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading"></div>
      <div class="panel-body">

        <div id="wizard1" class="wizard-type1">
          <ul class="steps">
            <li><a href="form-wizard.html#tab11" data-toggle="tab"><span class="badge badge-info">1</span> First</a></li>
            <li><a href="form-wizard.html#tab12" data-toggle="tab"><span class="badge badge-info">2</span> Second</a></li>
            <li><a href="form-wizard.html#tab13" data-toggle="tab"><span class="badge badge-info">3</span> Third</a></li>
          </ul>
          <div class="progress thin">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;"></div>
          </div>

          <div class="tab-content">
            <div class="tab-pane" id="tab11">
              <form class="form-horizontal" role="form">
                <div class="form-group">
                  <label class="col-md-3 control-label" for="email-w1">Email</label>
                    <div class="col-md-9">
                        <input type="email" id="email-w1" name="email-w1" class="form-control" placeholder="Enter Email..">
                        <span class="help-block">Please enter your email</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" for="password-w1">Password</label>
                    <div class="col-md-9">
                        <input type="password" id="password-w1" name="password-w1" class="form-control" placeholder="Enter Password..">
                        <span class="help-block">Please enter your password</span>
                    </div>
                </div>
              </form>
            </div>



            <div class="tab-pane" id="tab12">

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-feedback">
                      <label for="name-w1">Name</label>
                      <input type="text" class="form-control" id="name-w1" placeholder="Enter your name">
                    <span class="fa fa-asterisk form-control-feedback"></span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-sm-12">
                  <div class="form-group has-feedback">
                      <label for="ccnumber-w1">Credit Card Number</label>
                      <input type="text" class="form-control" id="ccnumber-w1" placeholder="0000 0000 0000 0000">
                    <span class="fa fa-asterisk form-control-feedback"></span>
                  </div>
                </div>
              </div>

            </div>


            <div class="tab-pane" id="tab13">

              <div class="form-group">
                <label for="company-w1">Company</label>
                <input type="text" class="form-control" id="company-w1" placeholder="Enter your company name">
              </div>


              <div class="form-group">
                <label for="country-w1">Country</label>
                <input type="text" class="form-control" id="country-w1" placeholder="Country name">
              </div>

              <div class="form-group">
                <div class="checkbox">
                  <label for="checkbox1-w1">
                  <input type="checkbox" id="checkbox1-w1" name="checkbox1-w1" value="option1"> I agree with <a href="form-wizard.html#">Terms</a></label>
                </div>
              </div>

            </div>
          </div>

          <div class="actions">
            <input type="button" class="btn btn-default button-previous" name="prev" value="Prev" />
            <input type="button" class="btn btn-success button-next" name="next" value="Next" />
            <input type="button" class="btn btn-primary button-finish" name="finish" value="Finish" style="display:none"/>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

{% block extra_script %}
  <script>
    $('.group_select').multiSelect({
    selectableHeader: "<input type='text' class='search-input' autocomplete='off'>",
    selectionHeader: "<input type='text' class='search-input' autocomplete='off'>",
    afterInit: function(ms){
      var that = this,
          $selectableSearch = that.$selectableUl.prev(),
          $selectionSearch = that.$selectionUl.prev(),
          selectableSearchString = '#'+that.$container.attr('id')+' .ms-elem-selectable:not(.ms-selected)',
          selectionSearchString = '#'+that.$container.attr('id')+' .ms-elem-selection.ms-selected';

      that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
      .on('keydown', function(e){
        if (e.which === 40){
          that.$selectableUl.focus();
          return false;
        }
      });

      that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
      .on('keydown', function(e){
        if (e.which == 40){
          that.$selectionUl.focus();
          return false;
        }
      });
    },
    afterSelect: function(){
      this.qs1.cache();
      this.qs2.cache();
    },
    afterDeselect: function(){
      this.qs1.cache();
      this.qs2.cache();
    }
    });
  </script>

  <script src="{% static "js/pages/form-wizard.js" %}"></script>

{% endblock extra_script %}

templates/group/group-overview.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}<h1>Groups overview</h1>{% endblock %}

{% block content %}

<div class="panel panel-info">
  <div class="panel-heading">
    <form class="form-inline pull-right" role="form">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search..." name='query_group'>
      </div>
    </form>
    <a href="{% url 'pupil:group' %}">
    <button class="btn btn-success">
        <i class="fa fa-plus-square" aria-hidden="true"></i>
    </button>
    </a>
  </div>
  <div class="panel-body no-padding-bottom">
    <div class="tab-content">
      {% if not groups %}
        <p>{% trans "Please add some groups" %}</p>
      {% else %}
        <table class="table table-bordered table-striped table-condensed">
          <thead>
            <tr>
              <th>{% trans 'University' %}</th>
              <th>{% trans 'Curator' %}</th>
              <th>{% trans 'Subjects' %}</th>
              <th>{% trans 'Department' %}</th>
              <th>{% trans 'Maximum/minimum' %}</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for group in groups %}

                <tr id = '{{ group.id }}'>
                  <td>{{ group.univer }}</td>
                  <td>{{ group.curator }}</td>
                  <td>{% for subject in group.subject.all %} {{subject}} {% endfor %}</td>
                  <td>{{ group.department }}</td>
                  <td>{{ group.maximum }}/{{ group.minimum }}</td>
                  <td>
                      <a href="{% url 'pupil:group_edit' group.id %}">
                          <button class="btn btn-primary">
                              <i class="fa fa-pencil-square"></i>
                          </button>
                      </a>
                      <button data="{{ group.id }}" class="btn btn-danger remove-iniv" id=delete>
                              <i class="fa fa-trash-o"></i>
                          </button>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

{% block extra_script %}
<script>

$('.remove-iniv').click(function(){
   gr_id = $(this).attr('data');
   $.ajax({type: "POST",
          url: "{% url 'pupil:group_delete' %}",
          data: {group_id: gr_id },
          success: function(){
            $('#'+gr_id).remove();

      }});
});
</script>
{% endblock extra_script %}