apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.sign_up, name='sign_up'),
    url(r'^success/$', views.success_registration, name='success'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},
        name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^email/$', views.EmailView.as_view(), name='email'),

]

apps/pupil/urls.py
from django.conf.urls import url

from . import api, views
from .forms import GroupForm1, GroupForm2, GroupForm3

urlpatterns = [
    url(r'^$', views.pupil_overview, name='overview'),
    url(r'^add/$', views.pupil_add, name='add'),
    url(r'^add_subject/$', api.add_subject, name='add_subject'),
    url(r'^edit/(?P<id>\d+)$', views.pupil_edit, name='edit'),
    url(r'^delete/$', api.pupil_delete, name='delete'),
    url(r'^group/$', views.GroupWizard.as_view([GroupForm1, GroupForm2, GroupForm3]), name='group'),
    url(r'^group/done/$', views.success_group_creation, name='group_success'),
    url(r'^group/overview/$', views.group_overview, name='group_overview'),
    url(r'^group/edit/(?P<id>\d+)$', views.group_edit, name='group_edit'),
    url(r'^group/delete/$', api.group_delete, name='group_delete'),
    ]

students/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = [
    url(r'^university/',
        include('apps.university.urls', namespace='university')),
    url(r'^lector/', include('apps.lector.urls', namespace='lector')),
    url(r'^pupil/', include('apps.pupil.urls', namespace='pupil')),
    url(r'^my_account/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'apps.accounts.views.home', name='home'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^resetpassword/passwordsent$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^resetpassword/$', auth_views.password_reset, name="reset_password"),
    url(r'^reset(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done$', auth_views.password_reset_complete, name='password_reset_complete'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block main_title %}First{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="University">
    <meta name="author" content="SwY">
    <meta name="keyword" content="University, Student, Lector">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- page css files -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/multi-select.css' %}" media="screen" rel="stylesheet" type="text/css">
    <script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
    <script src="{% static 'js/jquery.multi-select.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.quicksearch.js' %}" type="text/javascript"></script>
    <!-- Extra head -->
    {% block extra_head %}{% endblock extra_head %}
</head>

<body>
    {% block header %}
    <!-- start: Header -->
    <div class="navbar" role="navigation">
        <div class="container-fluid content">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                </button>
                <a class="navbar-brand" href="{% url 'university:overview' %}">University</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <!-- { if account.register == True } -->
                  <li><a href="{% url 'accounts:email' %}">Email verification</a></li>
                <!-- { endif } -->
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
            </ul>
        </div>
    </div>
    {% endblock header %}
    <div class="container-fluid content">
        <div class="row">
            {% block menu %}
            <div class="sidebar col-md-2 col-sm-1 ">
                <div class="sidebar-collapse collapse">
                    <div class="nav-sidebar title"><span>Main Menu</span></div>
                    <ul class="nav nav-sidebar">
                        <li>
                            <a href="{% url 'university:overview' %}">
                                <span class="hidden-sm text">Universities</span></a>
                        </li>
                        <li>
                            <a href="{% url 'lector:overview' %}">
                                <span class="hidden-sm text">Lectors</span></a>
                        </li>
                        <li>
                            <a href="{% url 'pupil:overview' %}">
                                <span class="hidden-sm text">Pupils</span></a>
                        </li>
                        <li>
                            <a href="{% url 'pupil:group_overview' %}">
                                <span class="hidden-sm text">Groups</span></a>
                        </li>
                    </ul>
                </div>
                <a id="main-menu-min" class="full visible-md visible-lg"><i class="fa fa-angle-double-left"></i></a>
            </div>
            {% endblock menu %}
            <div class="col-md-10 col-sm-11 main">
                {% block title %}{% endblock %} {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    <!-- start: JavaScript-->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/jquery-migrate-1.2.1.min.js" %}"></script>
    <!-- page scripts -->
    <script src="{% static "js/jquery-ui.min.js" %}"></script>
    <script src="{% static "js/jquery.sparkline.min.js" %}"></script>
    <script src="{% static "js/jquery.chosen.min.js" %}"></script>
    <script src="{% static "js/jquery.autosize.min.js" %}"></script>
    <script src="{% static "js/jquery.placeholder.min.js" %}"></script>
    <script src="{% static "js/jquery.bootstrap.wizard.min.js" %}"></script>
    <script src="{% static "js/jquery.maskedinput.min.js" %}"></script>
    <!-- theme scripts -->
    <script src="{% static "js/custom.min.js" %}"></script>
    <script src="{% static "js/core.min.js" %}"></script>
    {% block extra_script %}{% endblock extra_script %}
    <!-- end: JavaScript-->
</body>

</html>

templates/home.html
{% extends 'base.html' %} {% block content %} {% endblock %}